dataroot: %s
number: 10
pre_transforms:
  - transform: NormalizeScale
  - transform: GridSampling3D
    lparams: [0.02]
train_transforms:
  - transform: FixedPoints
    lparams: [%i]
test_transforms:
  - transform: FixedPoints
    lparams: [%i]